services:
  angular-app:
    build: .
    restart: always
    environment:
      BASE_URL: ${BASE_URL}
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "${EXPOSED_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - angular-app
