services:
  angular-app:
    build:
      context: .
      args:
        BASE_URL: ${BASE_URL}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "${EXPOSED_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - angular-app
